import type { FastifyPluginAsync } from 'fastify';
import { adminAuthRoutes } from './auth.js';
import { adminDashboardRoutes } from './dashboard.js';
import { adminArtistRoutes } from './artists.js';
import { adminAlbumRoutes } from './albums.js';
import { adminTrackRoutes } from './tracks.js';
import { adminEventRoutes } from './events.js';
import { adminVideoRoutes } from './videos.js';
import { adminServiceRoutes } from './services.js';
import { adminMediaRoutes } from './media.js';
import { adminInquiryRoutes } from './inquiries.js';
import { adminHomepageRoutes } from './homepage.js';
import { adminSiteSettingsRoutes } from './siteSettings.js';
import { adminPreWeddingRoutes } from './preWedding.js';
import { adminActivityLogRoutes } from './activityLogs.js';
import { adminUserManagementRoutes } from './adminUsers.js';

export const adminRoutes: FastifyPluginAsync = async (fastify) => {
  await fastify.register(adminAuthRoutes);
  await fastify.register(adminDashboardRoutes);
  await fastify.register(adminArtistRoutes);
  await fastify.register(adminAlbumRoutes);
  await fastify.register(adminTrackRoutes);
  await fastify.register(adminEventRoutes);
  await fastify.register(adminVideoRoutes);
  await fastify.register(adminServiceRoutes);
  await fastify.register(adminMediaRoutes);
  await fastify.register(adminInquiryRoutes);
  await fastify.register(adminHomepageRoutes);
  await fastify.register(adminSiteSettingsRoutes);
  await fastify.register(adminPreWeddingRoutes);
  await fastify.register(adminActivityLogRoutes);
  await fastify.register(adminUserManagementRoutes);
};
